### PR TITLE
resolve #118

### LINKED ISSUE #118: Use latest version from commit history instead latest greatest for unchanged modules
Hello Daniel,
first of all great work! I'm really looking forward to use this plugin. I played a lot with the bundled `dependencymanagement-using-parent-module-version-property` test project and found this issue that is a deal-breaker for us.

The plugin always uses the latest version for unchanged modules (info log: _Will use version [...] as it has not been changed since that release._) but this does not work for changes on different branches.

Imagine this little git example:
```
      C   topic
     /
    A---B master

A: initial commit; tags: util-1.0.1 app-1.0.1
B: change util; tags: util-1.0.2 app-1.0.2
C: change app; build fails (tries to use incompatible util-1.0.2)
```
Each commit gets released and commit B contains a breaking change in a util-module. Commit C only contains a change of the app-module (that uses the util-module). The release of C will fail because it detects no changes on util-module (which is correct) but uses the version build from commit B, which has changes in comparison to C.

I recommend to walk back the history of commit C and only use tags you find in this history as possible version candidates.

In my example the release of C should use util-1.0.1 to build app-1.0.3 and everything would be fine.

What do you think about this issue/suggestion?

### PR DESCRIPTION
**Pull request by nitschSB**
Hi,
I don't know if my changes have any performace issues.

I had serveral test errors:
```
[ERROR] Errors: 
[ERROR]   LocalGitRepoTest.usesThePassedInScmUrlToFindRemote:53 » Transport file:////hom...
[ERROR]   GitRelatedTest.ifThereIsNoRemoteButTheScmDetailsArePresentThenThisIsUsed:87 » MavenExecution
[ERROR]   MavenCompatibilityTest.maven_3_0_1:29->buildProjectWithMavenVersion:51 » MavenExecution
[ERROR]   MavenCompatibilityTest.maven_3_0_4:34->buildProjectWithMavenVersion:51 » MavenExecution
[ERROR]   MavenCompatibilityTest.maven_3_2_1:39->buildProjectWithMavenVersion:51 » MavenExecution
```
I don't know why.  In my project it works.

Cheers
Mario

### CODE REVIEW

**Comment by kobynet** [comment]
@danielflower Any chance to get this reviewed and merged anytime soon?

**Comment by kobynet** [comment]
@nitschSB can you update the PR with the latest master?

**Comment by nitschSB** [comment]
> @nitschSB can you update the PR with the latest master?

Done

**Comment by danielflower** [comment]
Thanks, released in `3.6.0`

**Pull request merged**
