### PR TITLE
Migrated JSR-330 to Plexus; Maven 3.0.x - 3.3x is supported now

### PR DESCRIPTION
**Pull request by SourcePond**
See my PR I closed recently for further information. The main thing I did since then is to migrate to Plexus as DI container. All required Maven versions are supported now :)

### CODE REVIEW

**Comment by SourcePond** [comment]
Hi Daniel,

I would like to ask you what the next steps are. Additionally to https://github.com/danielflower/multi-module-maven-release-plugin/issues/9, I fixed two further bugs in my fork which also occur with the original plugin:
- If you have a symbolic link to a local Maven repository and this link is referenced through Maven (either because ~/.m2/repository is a symlink or localRepository in the settings file references a symlink), then the build fails because the changed POMs cannot be reverted. This occurs at least on Linux or OSX.
- If you have dependencies in your POM which use properties as versions, the version property of those dependencies need to be substituted before further processing. Otherwise, necessary dependencies will not be updated, and, SNAPSHOT dependencies will not be detected.

I would like to ask you, if the fork can be pulled as the compatibility to Maven 3.0.x is proven now.

Have a nice day!
Roland

**Comment by danielflower** [comment]
Hi Roland. Sorry, just haven't been home for the last couple of weeks. Hopefully this weekend I can go through it all. Cheers!

**Comment by danielflower** [comment]
I'm getting the following when running the tests locally:

    Running e2e.ExecutionTest
    Installing the plugin into the local repo
    May 28, 2016 11:19:37 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
    INFO: I/O exception (java.net.SocketException) caught when processing request: Connection reset

Any idea why that would happen? What's happening when it installs into the sandboxed repo? Does it need some kind of connectivity to something?

**Comment by SourcePond** [comment]
I needs a connection to Maven central to download artifacts. I decided to maintain my own fork because I would like to do a lot more development on the plugin like supporting more SCMs (like Subversion) and SNAPSHOT version increment (like the maven-release-plugin does). Nevertheless, if you have questions or need support, don't hesitate to ask! If you are interested, you can find my fork here: https://github.com/SourcePond/multi-module-release-maven-plugin.git

Have a nice day,
Roland

**Pull request closed without merging**
