### PR TITLE
Refactoring to improve testability; upgrade to Maven 3.3 / Java 7

### PR DESCRIPTION
**Pull request by SourcePond**
Hi,

I refactored the plugin quite a bit. My objective was to bring the code into shape to improve its testability with mocks. This greatly improves speed when fixing bugs and writing appropriate tests. For this, I moved code into sub-packages, introduced facades and factories, and, upgraded the Maven Plugin API to 3.3.9 to make it possible to use dependency injection. Additionally, I upgraded the Java source level to 7. Because the API and Java upgrades, I incremented the plugin version to 1.5-SNAPSHOT. The introduction of facades has another advantage: it makes it possible to add support for further SCMs (like Mercurial).

Furthermore, I refactored the e2e tests such they use a private, local Maven repository to avoid pollution of the default repository. Lastly, I added following configuration properties:
- debugEnabled (BaseMojo, -X switch enabled during release build)
- stacktraceEnabled (BaseMojo, -e switch enabled during release build)
- localMavenRepo (ReleaseMojo, specifies -Dmaven.repo.local for release build)

The work is not finished yet, I'd like to refine the code where necessary, and, I'd like to add more unit tests to increase the test coverage to at least 90%. But, in my opinion, it has a good state now for further development.

Have a nice day!

### CODE REVIEW

**Comment by danielflower** [comment]
Wow, that's an impressive pull request :) Thanks!

It will take me a little while to go through this - going through the github diff is not very readable. But:

* I like the sound of have a private maven repo for testing
* Good to hear that more tests have moved to unit tests, as the tests really were taking way too long to run. I see the travis build still took 11 minutes though so still slow.

A couple of queries/concerns:

* Do you know if upgrading the maven plugin API to 3.3.9 has any effect on the versions of maven this supports?
* Changing to Java 7 is fine - I was planning to do that anyway to support the latest jgit (which solves some problems I've started seeing recently in jgit). But that's a breaking change, so the plugin version should move to 2.0-SNAPSHOT
* I'm a big fan of dependency injection, but constructors and the `new` keyword are the best approach imo. Frameworks like guice seem unnecessarily complicated, not that I noticed it when flicking through the diff.
* Adding the debug/stacktrace is good - but I think it might be possible to detect if those flags were enabled within the context of the current execution - would be better to use whatever the current values are rather than setting them explicitly as configurable properties, I think. I'm pretty sure it's possible, but not sure how.

Anyway, thanks. I'll try to go through the PR properly on my machine when I can.

**Comment by SourcePond** [comment]
Hi,

Sorry for my late answer, I was a little busy this week. Now, to your questions/concerns:

> Good to hear that more tests have moved to unit tests, as the tests really were taking way too long to run. I see the travis build still took 11 minutes though so still slow.
It's not my plan to replace any of the e2e-tests with unit-tests because they are great for integration testing. In my opinion, the plugins stability justifies the long build time. No, the unit tests will be added in addition.

> Do you know if upgrading the maven plugin API to 3.3.9 has any effect on the versions of maven this supports?
Yes, this has an impact. The plugin is only guaranteed to run with Maven 3.3+. I think, this is not really a problem because most developers use 3.3+ anyways. This includes online services like Travis or Cloudbees.

> Changing to Java 7 is fine - I was planning to do that anyway to support the latest jgit (which solves some problems I've started seeing recently in jgit). But that's a breaking change, so the plugin version should move to 2.0-SNAPSHOT
Agree

> I'm a big fan of dependency injection, but constructors and the new keyword are the best approach imo. Frameworks like guice seem unnecessarily complicated, not that I noticed it when flicking through the diff.
I don't agree at this point. The main problem with using the 'new' keyword and constructors directly is that you can't use mocks for testing at those points. When you use DI, you can inject a mock object instead; this led you focus on the code to be tested and avoids setting up large object graphs before you are even able to run through your code. Here is a small article: http://jasonpolites.github.io/tao-of-testing/ch3-1.1.html

> Adding the debug/stacktrace is good - but I think it might be possible to detect if those flags were enabled within the context of the current execution - would be better to use whatever the current values are rather than setting them explicitly as configurable properties, I think. I'm pretty sure it's possible, but not sure how.
I was investigating this but could not find a solution. For the moment, I would leave this flags to provide the ability to only affect the release-build which was started by the invoker. This can be useful for debugging when you not need the debug output from the main-build. But, I suggest to open an issue to preset this properties with information found in the context as default.

**Comment by SourcePond** [comment]
Hi,

I did some more work; mainly I moved the POM updater to its own package, covered it with unit tests, and, fixed https://github.com/danielflower/multi-module-maven-release-plugin/issues/9

Till now, there are still a lot of tests to be written but we are on a good way I think :)

**Comment by danielflower** [comment]
Okay, thanks for the response. So the Maven compatibility is very important to me - I know people using it with `3.0.3` (on some large teams it's difficult to upgrade everyone). So I don't want to break those. I have gone ahead with the java 7 requirement though, as I couldn't wait to fix the bug. So I've pushed the jgit upgrade and changed the version to `2.0-SNAPSHOT` (and am releasing as I type).

I also added a new test that tests the plugin against multiple versions of Maven itself: [MavenCompatibilityTest](https://github.com/danielflower/multi-module-maven-release-plugin/blob/master/src/test/java/e2e/MavenCompatibilityTest.java)

And with that I found the plugin supports Maven 3.0.1 or later. I want to keep it that way for as long as possible.

This is going to make it difficult to merge your change though, unfortunately. I'm not sure what the best way forward is - but certainly smaller PRs merged more frequently would be good though. The fix to #9 for example, and the logging stuff would be really great to get. I suppose it depends on if your branch can pass the Maven Compability tests.

As for dependency injection - I do love it. You don't need a framework for it though - you can just pass mocked objects into constructors. In a situation like this where Maven is creating the Mojo object, well that sucks but the simplest thing to do is create a proper constructor that just assigns dependencies, then create a parameter-less constructor that Maven will use and pass default values for the dependencies to the proper constructor.

I don't consider frameworks like Guice simple. Sure, they are not difficult to use, but what they do is create a huge amount of complexity, and then brush it under the rug. You don't see it until you get an exception with an unreadable stacktrace, or you want to do something that the framework didn't predict. If a little code can replace the use of a framework, I will go for that every time.

**Comment by SourcePond** [comment]
> I also added a new test that tests the plugin against multiple versions of Maven itself: MavenCompatibilityTest

I merged the test into the fork and did some little adjustments to the constructors where necessary. Maven 3.0.1 - 3.2.1 works internally with a Guice version which uses @com.google.inject.Inject whereas Maven > 3.3.0 uses javax.inject.Inject. With this change, the test passes.

> And with that I found the plugin supports Maven 3.0.1 or later. I want to keep it that way for as long as possible.

Ok, that should not be a problem, your new test will enforce that :)

> This is going to make it difficult to merge your change though, unfortunately. I'm not sure what the best way forward is - but certainly smaller PRs merged more frequently would be good though. The fix to #9 for example, and the logging stuff would be really great to get. I suppose it depends on if your branch can pass the Maven Compability tests.

Unfortunately, every commit floats into the PR from the point in time when I open it. So, when I do further development and commit changes to my master branch, all that stuff will end up automatically in the PR. The problem now is, that you need to do some manual merging. If you agree with the changes made, I would suggest to merge the code as all tests pass (and new ones will be added).

> As for dependency injection - I do love it. You don't need a framework for it though - you can just pass mocked objects into constructors

That is exatly what I do; for unit-testing I do not use any DI framework at all.

> In a situation like this where Maven is creating the Mojo object, well that sucks but the simplest thing to do is create a proper constructor that just assigns dependencies, then create a parameter-less constructor that Maven will use and pass default values for the dependencies to the proper constructor.

In this situation, I would not do that because Maven/Guice handle dependency injection properly. In my point of view, adding a parameterless constructor which calls another constructor with default values is unnecessary logic duplication here.

> I don't consider frameworks like Guice simple. Sure, they are not difficult to use, but what they do is create a huge amount of complexity, and then brush it under the rug. You don't see it until you get an exception with an unreadable stacktrace, or you want to do something that the framework didn't predict. If a little code can replace the use of a framework, I will go for that every time.

I understand you critsm about unreadable stacktraces when a dependency cannot be resolved. I have seen the same issue when I fixed the injection for Maven 3.0.1/3.2.1; in Maven 3.3> (with Guice 4) this is not a problem anymore. The exception messages are heaps better and point exactly to the location where the issue rises.

> If a little code can replace the use of a framework, I will go for that every time.
The framework is there as Maven uses it internally (previously Plexus, nowadays Guice). So, in my opinion, I doesn't make much sense to simply ignore it when we can use it for free :)

**Comment by SourcePond** [comment]
Your are right, http://maven.apache.org/maven-jsr330.html states that JSR330 is only supported from Maven 3.1.0 on. This means that @Inject can't be used and my PR cannot be merged now. I will add default constructors instead.

**Pull request closed without merging**
