### PR TITLE
Added support for custom private key and known_hosts

### PR DESCRIPTION
**Pull request by SourcePond**
Hi,

I found your cool plugin and added support for specifying a custom private key and/or known_hosts file. This is useful for build environments where you cannot rely on the defaults like ~/.ssh/id_rsa or ~/.ssh/known_hosts, for instance the CloudBees Jenkins cloud. In our case, it's not possible to upload a custom private key into ~/.ssh to access the Github repo because AFAIK no SSH access is granted on the Cloudbees Jenkins instance. This is ok, because the builds are executed on unpredictable nodes where the uploaded private key would not be available anyway. If we could specify a custom private-key / known_hosts file, then we were able to upload them into a special folder (which is available through Web-DAV during build), and, could reference it through the Maven settings-file or directly within the POM.

It would be great if you could review the pull request.

### CODE REVIEW

**Comment by danielflower** [comment]
Nice one!

Before I merge though, could you just add a couple of sentences to `src/site/markdown/usage.md.vm` explaining how for SSH URLs it will use `~/.ssh/id_rsa.pub` by default, but you can override that by setting the properties you added?

Maybe add a new section to that page called something like _Authentication with SSH URLs_

**Comment by SourcePond** [comment]
New documentation in usage.md.vm is ready to review.

**Comment by danielflower** [comment]
Good documentation. This has been released in version `1.4.4`

Thanks!

**Comment by SourcePond** [comment]
Wow, that was quick, thank you too!

**Pull request merged**
