### PR TITLE
Handle plugin dependencies

### PR DESCRIPTION
**Pull request by msaladin**
Hi there,

as proposed in issue [145](https://github.com/danielflower/multi-module-maven-release-plugin/issues/145) here is the PR to handle Plugin dependencies.

I created a testproject called openapi-spec-as-plugin-dependency which assures that interproject-plugin dependencies are automatically adjusted in a release.

If you have any questions, let me know. I am glad to be of assistance. 

Thanks & Cheers
Michael

### CODE REVIEW

**Comment by danielflower** [comment]
Thanks. The change itself looks good, but I don't really want to have to maintain things like spring versions, even if in a test dependency. Can you simplify the test project so it doesn't need extra dependencies?

**Comment by msaladin** [comment]
I wanted to be a realistic as possible, but you are right that Spring introduces a whole lot of complexity. Now I switched to another openapi generator (java/native) and a Dummy controller which actually does what it needs to do: Make sure that the generated classes exist by using them in a Java class that is compiled during the test execution, a real Rest controller is actually not needed. Hope that this is better.

**Review by danielflower — APPROVED** [review]

**Comment by msaladin** [comment]
Sorry, I see. I did execute the tests on my machine, and they worked fine. Now I added a github action, and I saw that the Java 8 build failed, and the Java 11 build suceeded. 

The reason for the failure with java 8 is:

```
Unable to load the mojo 'generate' in the plugin 'org.openapitools:openapi-generator-maven-plugin:7.8.0' 
```

The main idea with the test is:
* Run a real Maven project where one module contains openapi-spec
* And the other module uses the openapi generator to generate source code from the openapi-spec
* And assure that the correct version is used by running the Maven Build with -X, and then analying the output
* And assure that the generator was really invoked by using the generated classes in the source which is compiled with Maven

So it seems not to be possible with Java 8 to run the openapi-generator-maven-plugin, but of course Plugin dependencies can be tested with any plugin, it does not have to be the openapi-generator-maven-plugin.

I just wanted a test project which really makes sense. But honestly, I don't like running the Maven build with "-X" at all (too large output as you mentionned).

What do you propose?
* Should I stick with this kind of test, and just try with plugins that support Java 8?
* Should I remove the test completely as the changes to the code are minimal?
* Any other suggestion regarding how to test plugin dependencies?

Thanks & Cheers
Michael

**Comment by danielflower** [comment]
Sorry for the delayed response - making the test pass with Java 8 would be the best approach.

Changing the minimum Java version to 11 would be a very big breaking change so I can't do that currently.

Thanks.

**Comment by danielflower** [comment]
I think I'll need to revert this change until Java 8 is working with it.

**Pull request merged**
